リアルタイム通知画面のサンプル実装
shinonome-inc/pg_mobile pull request #11
Opened 2024-02-26 03:25 UTC by Yoshida-koshi

## 概要

## UI
<img src="" width="300">

## 動作確認

## 参考

2024-03-03 01:51 UTC, KobayashiYoh requested changes
コメントしました

2024-03-03 01:51 UTC, KobayashiYoh commented on lib/debug/debug_real_time_notification_page.dart
> +}
clientIdとclientSecretが差分に入っちゃっているので、ApiServiceを削除してMastodonRepositoryクラスを呼び出してサインインする感じに修正してもらっても良いですか？

2024-03-03 01:51 UTC, KobayashiYoh commented on lib/debug/debug_real_time_notification_page.dart
> +      );
👍

2024-03-03 01:51 UTC, KobayashiYoh commented on lib/debug/debug_real_time_notification_page.dart
> +    });
天才か！？

2024-03-04 03:37 UTC, Yoshida-koshi commented on lib/debug/debug_real_time_notification_page.dart
> +    });
yoくんでもできるよ笑笑

2024-03-04 03:59 UTC, Yoshida-koshi commented on lib/debug/debug_real_time_notification_page.dart
> +}
修正しました！ [d472ef9](https://github.com/shinonome-inc/pg_mobile/pull/11/commits/d472ef9996c746f67cb4e165f60b9cb5d0ce187e)

2024-03-05 03:03 UTC, KobayashiYoh approved these changes

2024-03-05 03:07 UTC, merged