画面遷移繋ぎこみ
shinonome-inc/pg_mobile pull request #3
Opened 2023-12-24 11:00 UTC by Ryunosuke1114

https://www.figma.com/file/1GZoEw6Chi0zPPjqQyuX0t?embed_host=notion&kind=file&mode=design&node-id=137-3634&t=VXG23zZQkkoXsHWE-0&type=design&viewer=1

画面遷移図のページ作成&繋ぎこみ

2024-01-25 09:21 UTC, KobayashiYoh requested changes
コメントしました

2024-01-25 09:21 UTC, KobayashiYoh commented on lib/bottom_navigation.dart
> +import 'package:pg_mobile/user/user_view.dart';
ディレクトリ構造だけNotionの内容に合わせてもらってもいいかな？
https://www.notion.so/MTG20240124-e30f24bb476d471cae8a6e4db598b731?pvs=4#26b34929656b466eb9f558e7526a12b6

2024-01-25 09:21 UTC, KobayashiYoh commented on lib/bottom_navigation.dart
> +    StateProvider<NavigationMenu>((ref) => NavigationMenu.home);
👍

2024-01-25 09:21 UTC, KobayashiYoh commented on lib/util.dart
> +  }
これもいいね👍

2024-01-25 09:22 UTC, KobayashiYoh commented
コンフリクトの修正もお願い🙏

2024-01-29 13:33 UTC, Ryunosuke1114 commented on lib/bottom_navigation.dart
> +import 'package:pg_mobile/user/user_view.dart';
pagesにまとめた！

2024-02-14 13:26 UTC, KobayashiYoh requested changes
コメントしました

ディレクトリ構造しっかり修正できています👍
ファイル名のタイプミスとコンフリクトの解消もお願いします

2024-02-14 13:26 UTC, KobayashiYoh commented on lib/pages/post/post.view.dart
> +
ファイル名がタイピングミスしてるよ

2024-02-26 06:27 UTC, Ryunosuke1114 commented on lib/pages/post/post.view.dart
> +
コンフリクトと一緒に直した！

2024-02-26 08:28 UTC, KobayashiYoh commented on lib/pages/post/post.view.dart
> +
ありがとー！

2024-02-28 14:39 UTC, KobayashiYoh approved these changes
LGTM！

2024-02-28 14:39 UTC, merged