お気に入り一覧画面実装
shinonome-inc/pg_mobile pull request #34
Opened 2024-04-15 09:47 UTC by Yoshida-koshi

## 概要

## UI
<img src="" width="300">

## 動作確認

## 参考

2024-04-21 07:43 UTC, KobayashiYoh requested changes
コメントしました。
本実装が絡む部分に関しては修正お願いします。

2024-04-21 07:43 UTC, KobayashiYoh commented on lib/views/status_view.dart
> +    return Padding(
DateFormatterクラスを使ってください。

2024-04-21 07:43 UTC, KobayashiYoh commented on lib/views/status_view.dart
> +                                style: Theme.of(context)
プロジェクト内の文字列は原則シングルクオーテーションで統一してください。
https://api.flutter.dev/flutter/widgets/Text-class.html

2024-04-21 07:43 UTC, KobayashiYoh commented on lib/views/status_view.dart
> +                        ),
タイムラインの実装時よりわかりやすいですね👍

2024-04-21 07:43 UTC, KobayashiYoh commented on lib/views/status_view.dart
> +                height: 56,
本実装のUI実装では、screen_utilを使用してください。

2024-04-21 07:43 UTC, KobayashiYoh commented on lib/repository/mastodon_repository.dart
> +      final favoriteStatusList = List<dynamic>.from(response.data);
さすが👏

2024-04-21 07:43 UTC, KobayashiYoh commented on lib/views/status_view.dart
> +  const StatusView({super.key, required this.status});
このプロジェクトのディレクトリ構造だと、lib/viewsではなくlib/widgetsが適切だと思われます。
https://github.com/shinonome-inc/pg_mobile/tree/develop?tab=readme-ov-file#%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E6%A7%8B%E9%80%A0

2024-04-29 04:51 UTC, Yoshida-koshi commented on lib/views/status_view.dart
> +    return Padding(
そもそもDateFormatter.formatPastDate関数の引数はDateTime型であり、status.createdAtはString型なので、20行目ではString型からDateTime型に変換する処理を書いています。

2024-04-29 04:53 UTC, Yoshida-koshi commented on lib/views/status_view.dart
> +                                style: Theme.of(context)
修正します！

2024-04-29 04:56 UTC, Yoshida-koshi commented on lib/views/status_view.dart
> +                height: 56,
修正します！

2024-04-29 05:13 UTC, Yoshida-koshi commented on lib/views/status_view.dart
> +  const StatusView({super.key, required this.status});
views無いのね。修正します！

2024-04-29 05:22 UTC, Yoshida-koshi commented on lib/views/status_view.dart
> +                                style: Theme.of(context)
修正しました！ [4304d2b](https://github.com/shinonome-inc/pg_mobile/pull/34/commits/4304d2b9f6c843ba18dc6002d6b0b3388a3b519d)

2024-04-29 05:22 UTC, Yoshida-koshi commented on lib/views/status_view.dart
> +                height: 56,
修正しました！ [f8a4dc2](https://github.com/shinonome-inc/pg_mobile/pull/34/commits/f8a4dc29e21198c0f89214df8b35074a843bcef8)

2024-04-29 05:23 UTC, Yoshida-koshi commented on lib/views/status_view.dart
> +  const StatusView({super.key, required this.status});
修正しました！ [e24677b](https://github.com/shinonome-inc/pg_mobile/pull/34/commits/e24677b495c3c9c69c5e0aae7eff5b9c0c67ec75)

2024-05-01 12:15 UTC, KobayashiYoh commented on lib/views/status_view.dart
> +    return Padding(
なるほど、申し訳ないです🙏

2024-05-01 12:16 UTC, KobayashiYoh approved these changes

2024-05-01 12:16 UTC, merged